// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.0
// 	protoc        (unknown)
// source: v1/command.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetListPodRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetListPodRequest) Reset() {
	*x = GetListPodRequest{}
	mi := &file_v1_command_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetListPodRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetListPodRequest) ProtoMessage() {}

func (x *GetListPodRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_command_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetListPodRequest.ProtoReflect.Descriptor instead.
func (*GetListPodRequest) Descriptor() ([]byte, []int) {
	return file_v1_command_proto_rawDescGZIP(), []int{0}
}

type GetListPodResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pods          []*Pod                 `protobuf:"bytes,1,rep,name=pods,proto3" json:"pods,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetListPodResponse) Reset() {
	*x = GetListPodResponse{}
	mi := &file_v1_command_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetListPodResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetListPodResponse) ProtoMessage() {}

func (x *GetListPodResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_command_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetListPodResponse.ProtoReflect.Descriptor instead.
func (*GetListPodResponse) Descriptor() ([]byte, []int) {
	return file_v1_command_proto_rawDescGZIP(), []int{1}
}

func (x *GetListPodResponse) GetPods() []*Pod {
	if x != nil {
		return x.Pods
	}
	return nil
}

var File_v1_command_proto protoreflect.FileDescriptor

var file_v1_command_proto_rawDesc = []byte{
	0x0a, 0x10, 0x76, 0x31, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x02, 0x76, 0x31, 0x1a, 0x0c, 0x76, 0x31, 0x2f, 0x70, 0x6f, 0x64, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x13, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x50,
	0x6f, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x31, 0x0a, 0x12, 0x47, 0x65, 0x74,
	0x4c, 0x69, 0x73, 0x74, 0x50, 0x6f, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x1b, 0x0a, 0x04, 0x70, 0x6f, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x07, 0x2e,
	0x76, 0x31, 0x2e, 0x50, 0x6f, 0x64, 0x52, 0x04, 0x70, 0x6f, 0x64, 0x73, 0x42, 0x63, 0x0a, 0x06,
	0x63, 0x6f, 0x6d, 0x2e, 0x76, 0x31, 0x42, 0x0c, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x50,
	0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x23, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x62, 0x75, 0x66, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x2f, 0x62, 0x75, 0x66, 0x2d,
	0x74, 0x6f, 0x75, 0x72, 0x2f, 0x67, 0x65, 0x6e, 0x2f, 0x76, 0x31, 0xa2, 0x02, 0x03, 0x56, 0x58,
	0x58, 0xaa, 0x02, 0x02, 0x56, 0x31, 0xca, 0x02, 0x02, 0x56, 0x31, 0xe2, 0x02, 0x0e, 0x56, 0x31,
	0x5c, 0x47, 0x50, 0x42, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0xea, 0x02, 0x02, 0x56,
	0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_v1_command_proto_rawDescOnce sync.Once
	file_v1_command_proto_rawDescData = file_v1_command_proto_rawDesc
)

func file_v1_command_proto_rawDescGZIP() []byte {
	file_v1_command_proto_rawDescOnce.Do(func() {
		file_v1_command_proto_rawDescData = protoimpl.X.CompressGZIP(file_v1_command_proto_rawDescData)
	})
	return file_v1_command_proto_rawDescData
}

var file_v1_command_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_v1_command_proto_goTypes = []any{
	(*GetListPodRequest)(nil),  // 0: v1.GetListPodRequest
	(*GetListPodResponse)(nil), // 1: v1.GetListPodResponse
	(*Pod)(nil),                // 2: v1.Pod
}
var file_v1_command_proto_depIdxs = []int32{
	2, // 0: v1.GetListPodResponse.pods:type_name -> v1.Pod
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_v1_command_proto_init() }
func file_v1_command_proto_init() {
	if File_v1_command_proto != nil {
		return
	}
	file_v1_pod_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_v1_command_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_v1_command_proto_goTypes,
		DependencyIndexes: file_v1_command_proto_depIdxs,
		MessageInfos:      file_v1_command_proto_msgTypes,
	}.Build()
	File_v1_command_proto = out.File
	file_v1_command_proto_rawDesc = nil
	file_v1_command_proto_goTypes = nil
	file_v1_command_proto_depIdxs = nil
}
