// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: client/controller/v1/service.proto

package v1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/bufbuild/buf-tour/gen/client/controller/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// ControllerServiceName is the fully-qualified name of the ControllerService service.
	ControllerServiceName = "v1.ControllerService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// ControllerServiceGetListEndpointProcedure is the fully-qualified name of the ControllerService's
	// GetListEndpoint RPC.
	ControllerServiceGetListEndpointProcedure = "/v1.ControllerService/GetListEndpoint"
)

// These variables are the protoreflect.Descriptor objects for the RPCs defined in this package.
var (
	controllerServiceServiceDescriptor               = v1.File_client_controller_v1_service_proto.Services().ByName("ControllerService")
	controllerServiceGetListEndpointMethodDescriptor = controllerServiceServiceDescriptor.Methods().ByName("GetListEndpoint")
)

// ControllerServiceClient is a client for the v1.ControllerService service.
type ControllerServiceClient interface {
	GetListEndpoint(context.Context, *connect.Request[v1.GetListEndpointRequest]) (*connect.Response[v1.GetListEndpointResponse], error)
}

// NewControllerServiceClient constructs a client for the v1.ControllerService service. By default,
// it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and
// sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC()
// or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewControllerServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) ControllerServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	return &controllerServiceClient{
		getListEndpoint: connect.NewClient[v1.GetListEndpointRequest, v1.GetListEndpointResponse](
			httpClient,
			baseURL+ControllerServiceGetListEndpointProcedure,
			connect.WithSchema(controllerServiceGetListEndpointMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
	}
}

// controllerServiceClient implements ControllerServiceClient.
type controllerServiceClient struct {
	getListEndpoint *connect.Client[v1.GetListEndpointRequest, v1.GetListEndpointResponse]
}

// GetListEndpoint calls v1.ControllerService.GetListEndpoint.
func (c *controllerServiceClient) GetListEndpoint(ctx context.Context, req *connect.Request[v1.GetListEndpointRequest]) (*connect.Response[v1.GetListEndpointResponse], error) {
	return c.getListEndpoint.CallUnary(ctx, req)
}

// ControllerServiceHandler is an implementation of the v1.ControllerService service.
type ControllerServiceHandler interface {
	GetListEndpoint(context.Context, *connect.Request[v1.GetListEndpointRequest]) (*connect.Response[v1.GetListEndpointResponse], error)
}

// NewControllerServiceHandler builds an HTTP handler from the service implementation. It returns
// the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewControllerServiceHandler(svc ControllerServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	controllerServiceGetListEndpointHandler := connect.NewUnaryHandler(
		ControllerServiceGetListEndpointProcedure,
		svc.GetListEndpoint,
		connect.WithSchema(controllerServiceGetListEndpointMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	return "/v1.ControllerService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case ControllerServiceGetListEndpointProcedure:
			controllerServiceGetListEndpointHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedControllerServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedControllerServiceHandler struct{}

func (UnimplementedControllerServiceHandler) GetListEndpoint(context.Context, *connect.Request[v1.GetListEndpointRequest]) (*connect.Response[v1.GetListEndpointResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("v1.ControllerService.GetListEndpoint is not implemented"))
}
